apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-service
spec:
  type: LoadBalancer
  selector:
    app: mongodb-deployment
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-deployment
  template:
    metadata:
      labels:
        app: mongodb-deployment
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
          - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "root"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "example"
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
      - name: mongodb-express
        image: mongo-express
        ports:
          - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            value: "root"
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            value: "example"
          - name: ME_CONFIG_MONGODB_URL
            value: "mongodb://root:example@mongo:27017/"
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017