apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-service
spec:
  type: LoadBalancer
  selector:
    app: mongodb-express-deployment
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express-deployment
  labels:
    app: mongodb-express-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-express-deployment
  template:
    metadata:
      labels:
        app: mongodb-express-deployment
    spec:
      containers:
      - name: mongodb-express
        image: mongo-express
        ports:
          - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            value: "root"
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            value: "example"
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                  name: mongodb-configmap
                  key: database_url
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"

